---
title: "Why Reports & Report Writing Guide"
editor: visual
format: 
  html:
    toc: true
    number-sections: true
---

## Why Write Reports?

Many (if not all) challenges you complete will require a report. But why reports?

Reports are the most common medium for communicating your results. Their universality ensures that every participant, regardless of the project they choose, can produce a standardized output. However, if you have other ideas for presenting your results, we welcome your creativity and innovation.

Reports can be submitted <a href='/submission'>here</a> and should be in HTML or PDF format.

## How to Write Reports

Since no one wants to spend their holidays writing lengthy assessment-grade reports, the standard report has been simplified to a few key questions relevant to your project. Attached to each problem, you’ll find approximately **three questions** designed to help readers better understand your work. However, consider these as guidelines only—if you wish to include more details or go above and beyond to showcase your work, it will be greatly appreciated.

The three questions are designed as short-answer prompts, with a suggested guideline of approximately 200 words per question—or as many words as you need to convey your ideas.

**Remember**: That data science results are only as useful as they are inteligable. For the sake of your reader, the communication is just as useful as the results themself.

Below, you’ll find several sections on software tools that can help you create professional, polished reports, including those with code blocks. However, if you’re comfortable using regular Excel, feel free to continue with that.

### Rstudio

*For those with experience having complete data1001 or data2x02, you may skip this section.*

RStudio is a software primarily designed for academic data exploration and statistics using the R programming language. It also includes features like Quarto and an easy way to knit R Markdown (.rmd) and Quarto (.qmd) files.

to get started you will want to install <a href="https://posit.co/download/rstudio-desktop/"> rstudio</a>. 

::: {.column-margin}
To run reticulate (the r extension that enables python) you will need to seperately install python <a href=https://www.python.org/downloads/> here</a>.
:::

Once you get rstudio working you can use one of the many existing templates in a rmd or qmd file, or use a yaml header at the top of your document. Then in the application you can run 'knit' to produce a pdf or html document. 

```{yaml}
---
title: "Sample Quarto Document"
author: "Your Name"
date: "`r Sys.Date()`"
format: 
  html: 
    toc: true
    toc-depth: 2
    code-fold: true
  pdf: 
    keep-tex: true
    number-sections: true
abstract: |
  This is a sample Quarto document. 
  It demonstrates the use of YAML metadata for customization.
params:
  example_param: "default_value"
editor: visual
---
```

If you are working with RStudio there are many templates available for your use. One such can be found in the footer (rticles). 


### Quarto 

If you prefer using the CLI, you can use Quarto directly from the command line. Creating a Quarto file is as simple as adding a header like the one above, and then running quarto render file.qmd in the command line (assuming Quarto is installed).

## A Few More Things

Considerations for Report Writing:

*What is the background of my reader?*
You can assume that your readers are your peers—university students in data science or related fields.

**Graphs!**
A picture is worth a thousand words, and graphs are an effective way to communicate ideas. Including graphs in Quarto and R Markdown (.rmd) files is particularly easy, as your output can be "knitted" directly into the report. Alternatively, including a graph as a screenshot is a great way to demonstrate your points.

**Innovation**
While the questions provide a general direction for tackling the challenge or exploring the dataset, we encourage you to think creatively. If you believe there’s a more pressing question to explore, feel free to pursue it instead of sticking strictly to the suggested ones. Remember, these questions are simply prompts to inspire discussion and analysis of the dataset, summary, or model you've produced. Be innovative and try to stand out among your peers!

General Report Guidelines:
As always, standard report-writing principles apply. Discuss the limitations of your work and be transparent. Stick to a clear structure, but there’s no need for citations. Be concise—if you're using language models for writing, ensure the content is direct and doesn't waste the reader’s time. When submitting, take advantage of the "GitHub" section to include the code that produced your findings.

**Good luck with your writing!**
